# Generated by Django 3.1.1 on 2020-09-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('numero_guia', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_medico', models.IntegerField()),
                ('nome_medico', models.CharField(max_length=100)),
                ('data_consulta', models.DateField()),
                ('valor_consulta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia_consulta', models.IntegerField()),
                ('exame', models.CharField(max_length=100)),
                ('valor_exame', models.FloatField()),
            ],
        ),
    ]
