# Generated by Django 3.1.1 on 2020-09-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busca_consultas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exames',
            new_name='Exame',
        ),
    ]
