# Generated by Django 3.1.1 on 2020-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_consultas', '0003_auto_20200924_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.IntegerField()),
                ('nome_medico', models.CharField(max_length=100)),
                ('data_consulta', models.DateField()),
                ('valor_consulta', models.FloatField()),
                ('gasto_consulta', models.FloatField()),
                ('qtde_exames', models.IntegerField()),
            ],
        ),
    ]
